"""Report email delivery via SMTP.

Sends the "Email Report" export as a link-bearing HTML email (the file
itself stays on the server; the recipient opens the public URL). Falls
back gracefully when SMTP is not configured.
"""
import logging
import smtplib
from email.message import EmailMessage

from app.core.config import settings

logger = logging.getLogger("market_mind_ai.email")


class EmailNotConfiguredError(Exception):
    """Raised when SMTP is not configured but an email is requested."""


class EmailSendError(Exception):
    """Raised when SMTP delivery fails."""


class EmailService:
    """Deliver report emails using the configured SMTP settings."""

    def is_configured(self) -> bool:
        return bool(settings.SMTP_HOST and settings.SMTP_FROM)

    def send_report_email(
        self,
        *,
        to_email: str,
        business_name: str,
        public_url: str,
        summary: str = "",
    ) -> None:
        """Send a report email containing a link to the exported file."""
        if not self.is_configured():
            raise EmailNotConfiguredError(
                "Email delivery is not configured (SMTP_HOST / SMTP_FROM)."
            )

        message = EmailMessage()
        message["Subject"] = f"Your Market Mind AI report — {business_name}"
        message["From"] = f"{settings.REPORT_FROM_NAME} <{settings.SMTP_FROM}>"
        message["To"] = to_email

        body = (
            f"Hello,\n\n"
            f"Your marketing strategy report for <b>{business_name}</b> is ready.\n\n"
            f"Open it here: {public_url}\n\n"
        )
        if summary:
            body += f"Summary: {summary}\n\n"
        body += (
            "This report was generated by Market Mind AI.\n"
            "If you did not request it, you can safely ignore this email."
        )
        # Plain text + HTML parts.
        message.set_content(body.replace("<b>", "").replace("</b>", ""))
        message.add_alternative(
            f"""<html><body style="font-family:Arial,Helvetica,sans-serif;color:#1e293b">
<p>Hello,</p>
<p>Your marketing strategy report for <b>{business_name}</b> is ready.</p>
<p><a href="{public_url}"
   style="display:inline-block;padding:12px 20px;background:#4f46e5;color:#fff;
          text-decoration:none;border-radius:8px;font-weight:bold;">Open report</a></p>
{f"<p>{summary}</p>" if summary else ""}
<p style="color:#64748b;font-size:12px">Generated by Market Mind AI.
If you did not request this report, you can safely ignore this email.</p>
</body></html>""",
            subtype="html",
        )

        try:
            self._deliver(message)
        except EmailNotConfiguredError:
            raise
        except Exception as exc:
            logger.exception("Failed to send report email to %s", to_email)
            raise EmailSendError(f"Could not send the email: {exc}") from exc

        logger.info("Report email sent to %s for %s", to_email, business_name)

    def _deliver(self, message: EmailMessage) -> None:
        """Open an SMTP connection and send the message."""
        if settings.SMTP_USE_TLS:
            with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=30) as server:
                server.starttls()
                if settings.SMTP_USERNAME:
                    server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
                server.send_message(message)
        else:
            with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=30) as server:
                if settings.SMTP_USERNAME:
                    server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
                server.send_message(message)
