"""Report email delivery via SMTP.

Sends the "Email Report" export as a professional HTML email with the
report attached (PDF/DOCX/PPTX) plus a public download link. Falls
back gracefully when SMTP is not configured.
"""
import logging
import mimetypes
import smtplib
import ssl
from email.message import EmailMessage
from pathlib import Path

from app.core.config import settings

logger = logging.getLogger("market_mind_ai.email")


class EmailNotConfiguredError(Exception):
    """Raised when SMTP is not configured but an email is requested."""


class EmailSendError(Exception):
    """Raised when SMTP delivery fails."""


class EmailService:
    """Deliver report emails using the configured SMTP settings."""

    def is_configured(self) -> bool:
        return bool(
            settings.SMTP_HOST
            and settings.SMTP_FROM
            and settings.SMTP_USERNAME
            and settings.SMTP_PASSWORD
        )

    def _tls(self) -> bool:
        return settings.smtp_use_tls

    def send_report_email(
        self,
        *,
        to_email: str,
        business_name: str,
        public_url: str,
        summary: str = "",
        attachment_path: str | Path | None = None,
        attachment_display_name: str | None = None,
    ) -> None:
        """Send a report email with an optional attachment and a link."""
        if not self.is_configured():
            raise EmailNotConfiguredError(
                "Email delivery is not configured (SMTP_HOST / SMTP_FROM / "
                "SMTP_USERNAME / SMTP_PASSWORD). Add the SMTP_* variables to "
                ".env to enable email reports."
            )

        message = EmailMessage()
        message["Subject"] = f"Your Market Mind AI report — {business_name}"
        message["From"] = f"{settings.REPORT_FROM_NAME} <{settings.SMTP_FROM}>"
        message["To"] = to_email

        # Plain-text fallback.
        text = (
            f"Hello,\n\n"
            f"Your marketing strategy report for {business_name} is ready.\n\n"
            f"Open it here: {public_url}\n"
            + (f"\nSummary: {summary}\n" if summary else "")
            + "\nThis report was generated by Market Mind AI.\n"
            "If you did not request it, you can safely ignore this email."
        )
        message.set_content(text)

        message.add_alternative(self._render_html(business_name, public_url, summary), subtype="html")

        if attachment_path:
            path = Path(attachment_path)
            if path.is_file():
                mime, _ = mimetypes.guess_type(path.name)
                maintype, subtype = (
                    (mime.split("/", 1) if mime else ("application", "octet-stream"))
                )
                display = attachment_display_name or path.name
                message.add_attachment(
                    path.read_bytes(),
                    maintype=maintype,
                    subtype=subtype,
                    filename=display,
                )
            else:
                logger.warning(
                    "Attachment missing for report email to %s: %s",
                    to_email,
                    path,
                )

        try:
            self._deliver(message)
        except EmailNotConfiguredError:
            raise
        except Exception as exc:
            logger.exception("Failed to send report email to %s", to_email)
            raise EmailSendError(
                f"Could not send the email: {exc}"
            ) from exc

        logger.info("Report email sent to %s for %s", to_email, business_name)

    def _render_html(self, business_name: str, public_url: str, summary: str) -> str:
        """Professional branded HTML email with logo, summary and CTA."""
        from html import escape

        name = escape(business_name)
        url = escape(public_url)
        summary_html = (
            f'<p style="margin:18px 0 0;font-size:14px;line-height:1.7;color:#64748b;">'
            f"{escape(summary)}</p>"
            if summary
            else ""
        )
        return f"""<!doctype html>
<html lang="en">
<body style="margin:0;padding:0;background-color:#f1f5f9;font-family:Arial,Helvetica,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f1f5f9;padding:32px 12px;">
    <tr>
      <td align="center">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e2e8f0;">
          <tr>
            <td style="background:linear-gradient(135deg,#4f46e5 0%,#7c3aed 100%);padding:28px 32px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td>
                    <span style="font-size:22px;font-weight:bold;color:#ffffff;">&#9889; Market Mind AI</span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td style="padding:32px;">
              <h1 style="margin:0 0 8px;font-size:22px;color:#0f172a;line-height:1.3;">
                Your marketing strategy report is ready
              </h1>
              <p style="margin:0;font-size:14px;color:#475569;">Prepared for <strong style="color:#4f46e5;">{name}</strong></p>

              <p style="margin:18px 0 0;font-size:15px;line-height:1.7;color:#334155;">
                We have generated a complete, structured marketing strategy for your business.
                The report is attached to this email and available for download through the
                button below.
              </p>
              {summary_html}
              <table role="presentation" cellpadding="0" cellspacing="0" style="margin:28px 0 0;">
                <tr>
                  <td style="background-color:#4f46e5;border-radius:10px;">
                    <a href="{url}" target="_blank" style="display:inline-block;padding:14px 28px;font-size:15px;font-weight:bold;color:#ffffff;text-decoration:none;">
                      Download report
                    </a>
                  </td>
                </tr>
              </table>
              <p style="margin:28px 0 0;font-size:13px;color:#94a3b8;line-height:1.6;">
                The file is also attached to this email for convenience.<br/>
                Generated by Market Mind AI — if you did not request this report, you can
                safely ignore this email.
              </p>
            </td>
          </tr>
          <tr>
            <td style="padding:18px 32px;background-color:#f8fafc;border-top:1px solid #e2e8f0;">
              <p style="margin:0;font-size:12px;color:#94a3b8;">
                &copy; {business_name} &middot; Market Mind AI &middot; AI-powered marketing intelligence
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>"""

    def send_invitation_email(
        self,
        *,
        to_email: str,
        full_name: str | None,
        accept_url: str,
        invited_by: str,
    ) -> None:
        """Send a branded invitation email with an accept link."""
        if not self.is_configured():
            raise EmailNotConfiguredError(
                "Email delivery is not configured (SMTP_HOST / SMTP_FROM / "
                "SMTP_USERNAME / SMTP_PASSWORD). Add the SMTP_* variables to "
                ".env to enable invitations."
            )

        from html import escape

        name = escape(full_name or "there")
        url = escape(accept_url)
        inviter = escape(invited_by)

        message = EmailMessage()
        message["Subject"] = "You're invited to Market Mind AI"
        message["From"] = f"{settings.REPORT_FROM_NAME} <{settings.SMTP_FROM}>"
        message["To"] = to_email

        message.set_content(
            f"Hello {name},\n\n"
            f"{inviter} invited you to join Market Mind AI.\n\n"
            f"Accept the invitation here: {accept_url}\n\n"
            "The link expires in 7 days.\n"
            "If you did not expect this invitation, you can safely ignore it."
        )
        message.add_alternative(
            f"""<!doctype html>
<html lang="en">
<body style="margin:0;padding:0;background-color:#f1f5f9;font-family:Arial,Helvetica,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f1f5f9;padding:32px 12px;">
    <tr><td align="center">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e2e8f0;">
        <tr>
          <td style="background:linear-gradient(135deg,#4f46e5 0%,#7c3aed 100%);padding:28px 32px;">
            <span style="font-size:22px;font-weight:bold;color:#ffffff;">&#9889; Market Mind AI</span>
          </td>
        </tr>
        <tr>
          <td style="padding:32px;">
            <h1 style="margin:0 0 8px;font-size:22px;color:#0f172a;">You're invited</h1>
            <p style="margin:0;font-size:14px;color:#475569;">
              <strong style="color:#4f46e5;">{inviter}</strong> invited you to join Market Mind AI.
            </p>
            <p style="margin:18px 0 0;font-size:15px;line-height:1.7;color:#334155;">
              Create your account to start generating AI-powered marketing strategies,
              market analysis, customer personas, and campaigns in seconds.
            </p>
            <table role="presentation" cellpadding="0" cellspacing="0" style="margin:28px 0 0;">
              <tr>
                <td style="background-color:#4f46e5;border-radius:10px;">
                  <a href="{url}" target="_blank" style="display:inline-block;padding:14px 28px;font-size:15px;font-weight:bold;color:#ffffff;text-decoration:none;">
                    Accept invitation
                  </a>
                </td>
              </tr>
            </table>
            <p style="margin:28px 0 0;font-size:13px;color:#94a3b8;line-height:1.6;">
              This link expires in 7 days. If you did not expect this invitation,
              you can safely ignore this email.
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>""",
            subtype="html",
        )

        try:
            self._deliver(message)
        except Exception as exc:
            logger.exception("Failed to send invitation to %s", to_email)
            raise EmailSendError(f"Could not send the invitation: {exc}") from exc

        logger.info("Invitation email sent to %s", to_email)

    def _deliver(self, message: EmailMessage) -> None:
        """Open an SMTP connection and send the message."""
        host = settings.SMTP_HOST
        port = settings.SMTP_PORT
        timeout = 30

        if port == 465 or (not self._tls() and port == 465):
            # Implicit TLS (SMTPS).
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(host, port, timeout=timeout, context=context) as server:
                if settings.SMTP_USERNAME:
                    server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
                server.send_message(message)
            return

        with smtplib.SMTP(host, port, timeout=timeout) as server:
            server.ehlo()
            if self._tls():
                server.starttls(context=ssl.create_default_context())
                server.ehlo()
            if settings.SMTP_USERNAME:
                server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            server.send_message(message)
