"""Industry playbooks — the core of strategy uniqueness.

Each playbook encodes what a senior consultant knows about marketing in
that vertical: the channels that actually work, ad platforms, content
types, influencer strategy, typical KPIs, positioning angles, SEO terms
and email angles. The prompt injects the matching playbook and the
fallback mock uses it directly, so a restaurant never receives a SaaS
plan and vice versa.

Industry keys are lowercase substrings matched against the user's
``industry`` input (e.g. "Restaurant", "SaaS", "Gym & Fitness").
"""
from __future__ import annotations

INDUSTRY_PLAYBOOKS: dict[str, dict] = {
    "restaurant": {
        "keywords": ["restaurant", "cafe", "food", "dining", "kitchen", "bistro", "takeaway"],
        "channels": ["Google Business Profile", "Instagram", "Food Delivery Apps", "Facebook", "Local SEO"],
        "ad_platforms": ["Google Ads (Local)", "Meta Ads", "Instagram Ads", "Food Delivery App Promotions"],
        "content_types": ["Food photography", "Behind-the-scenes kitchen reels", "Menu highlights", "Customer reviews", "Chef stories"],
        "influencers": ["Local food influencers", "Micro food bloggers", "Instagram foodies"],
        "kpis": ["Online orders", "Dine-in reservations", "Google reviews", "Delivery app rating", "Repeat visits"],
        "positioning": "Position the restaurant around a signature dish, fresh ingredients and a memorable local dining experience.",
        "social_platforms": ["Instagram", "TikTok", "Facebook"],
        "seo_terms": ["best {city} restaurant", "restaurants near me", "{cuisine} in {city}", "best {dish} {city}"],
        "email_angles": ["Seasonal offers", "Weekend promotions", "Loyalty club", "New menu launches", "Event nights"],
        "tactics": [
            "Claim and optimize Google Business Profile with menus, photos and reviews",
            "Post daily food photography and short reels",
            "Partner with local food influencers for reviews",
            "Run promotions on delivery apps to boost ranking",
            "Create seasonal offers and weekend specials",
        ],
    },
    "saas": {
        "keywords": ["saas", "software", "tech", "app", "startup", "platform", "cloud", "b2b software"],
        "channels": ["LinkedIn", "Google Search Ads", "Product Hunt", "Technical Blogs", "Email Funnels", "Demo Booking"],
        "ad_platforms": ["Google Search Ads", "LinkedIn Ads", "YouTube Ads"],
        "content_types": ["Technical blog posts", "Product demos", "Case studies", "Comparison guides", "Webinars"],
        "influencers": ["Industry analysts", "Tech YouTubers", "SaaS newsletter authors"],
        "kpis": ["Free trial signups", "Demo bookings", "Activation rate", "Monthly recurring revenue", "Churn"],
        "positioning": "Position the software around a sharp outcome (time saved, revenue, automation) with a clear wedge vs incumbents.",
        "social_platforms": ["LinkedIn", "X", "YouTube"],
        "seo_terms": ["{product} alternative", "best {category} software", "{category} for {segment}", "{product} vs {competitor}"],
        "email_angles": ["Trial activation", "Feature launches", "Champion enablement", "Renewal reminders", "Webinar invites"],
        "tactics": [
            "Run Google Search Ads on high-intent category and competitor keywords",
            "Build a demo-booking campaign for qualified leads",
            "Launch on Product Hunt and tech communities",
            "Publish technical blogs and comparison guides",
            "Build an email funnel from trial signup to activation",
        ],
    },
    "software": {
        "keywords": ["software", "saas", "tech", "app", "platform", "cloud"],
        "channels": ["LinkedIn", "Google Search Ads", "Product Hunt", "Technical Blogs", "Email Funnels", "Demo Booking"],
        "ad_platforms": ["Google Search Ads", "LinkedIn Ads", "YouTube Ads"],
        "content_types": ["Technical blog posts", "Product demos", "Case studies", "Comparison guides", "Webinars"],
        "influencers": ["Industry analysts", "Tech YouTubers", "SaaS newsletter authors"],
        "kpis": ["Free trial signups", "Demo bookings", "Activation rate", "Monthly recurring revenue", "Churn"],
        "positioning": "Position the software around a sharp outcome with a clear wedge vs incumbents.",
        "social_platforms": ["LinkedIn", "X", "YouTube"],
        "seo_terms": ["{product} alternative", "best {category} software", "{category} for {segment}", "{product} vs {competitor}"],
        "email_angles": ["Trial activation", "Feature launches", "Champion enablement", "Renewal reminders", "Webinar invites"],
        "tactics": [
            "Run Google Search Ads on high-intent category and competitor keywords",
            "Build a demo-booking campaign for qualified leads",
            "Launch on Product Hunt and tech communities",
            "Publish technical blogs and comparison guides",
            "Build an email funnel from trial signup to activation",
        ],
    },
    "gym": {
        "keywords": ["gym", "fitness", "workout", "training", "crossfit", "yoga", "pilates", "wellness"],
        "channels": ["Instagram", "TikTok", "Facebook", "Google Business Profile", "Referral Program"],
        "ad_platforms": ["Meta Ads", "Instagram Ads", "Google Ads (Local)"],
        "content_types": ["Transformation videos", "Workout tutorials", "Trainer spotlights", "Member stories", "Before/after"],
        "influencers": ["Fitness influencers", "Local athletes", "Nano fitness creators"],
        "kpis": ["Membership signups", "Trial bookings", "Retention rate", "Class attendance", "Referrals"],
        "positioning": "Position the gym around tangible transformations, coaching quality and a motivating community.",
        "social_platforms": ["Instagram", "TikTok", "YouTube"],
        "seo_terms": ["gym near me", "personal trainer {city}", "best gym {city}", "fitness classes {city}"],
        "email_angles": ["Trial offers", "Member success stories", "New classes", "Referral rewards", "Re-engagement"],
        "tactics": [
            "Post daily transformation videos and workout reels",
            "Run nearby-audience Facebook and Instagram ads",
            "Build a referral campaign for existing members",
            "Partner with fitness influencers for try-outs",
            "Optimize Google Business Profile for local discovery",
        ],
    },
    "fitness": {
        "keywords": ["fitness", "gym", "workout", "training", "yoga", "pilates", "wellness"],
        "channels": ["Instagram", "TikTok", "Facebook", "Google Business Profile", "Referral Program"],
        "ad_platforms": ["Meta Ads", "Instagram Ads", "Google Ads (Local)"],
        "content_types": ["Transformation videos", "Workout tutorials", "Trainer spotlights", "Member stories", "Before/after"],
        "influencers": ["Fitness influencers", "Local athletes", "Nano fitness creators"],
        "kpis": ["Membership signups", "Trial bookings", "Retention rate", "Class attendance", "Referrals"],
        "positioning": "Position the fitness brand around tangible transformations, coaching quality and community.",
        "social_platforms": ["Instagram", "TikTok", "YouTube"],
        "seo_terms": ["fitness near me", "personal trainer {city}", "best gym {city}", "workout classes {city}"],
        "email_angles": ["Trial offers", "Member success stories", "New classes", "Referral rewards", "Re-engagement"],
        "tactics": [
            "Post daily transformation videos and workout reels",
            "Run nearby-audience Facebook and Instagram ads",
            "Build a referral campaign for existing members",
            "Partner with fitness influencers for try-outs",
            "Optimize Google Business Profile for local discovery",
        ],
    },
    "real estate": {
        "keywords": ["real estate", "property", "agency", "realtor", "homes", "apartments", "estate"],
        "channels": ["Google Search Ads", "Facebook Lead Ads", "Property Portals", "WhatsApp Automation", "CRM Integration"],
        "ad_platforms": ["Google Search Ads", "Facebook Lead Ads", "Instagram Ads"],
        "content_types": ["Property videos", "Virtual tours", "Neighborhood guides", "Listing walkthroughs", "Client testimonials"],
        "influencers": ["Local property influencers", "Interior design creators", "Neighborhood vloggers"],
        "kpis": ["Qualified leads", "Viewings booked", "Listings sold", "Lead-to-visit rate", "Response time"],
        "positioning": "Position the agency around market expertise, fast response and a frictionless buying/selling experience.",
        "social_platforms": ["Instagram", "Facebook", "YouTube", "LinkedIn"],
        "seo_terms": ["homes for sale {city}", "real estate agent {city}", "{city} property prices", "buy {city} apartment"],
        "email_angles": ["New listings", "Open house invites", "Market reports", "Price drops", "Mortgage tips"],
        "tactics": [
            "Run Google Search Ads on high-intent buying keywords",
            "Use Facebook Lead Ads with instant lead forms",
            "Produce professional property videos and virtual tours",
            "Automate follow-up via WhatsApp and a CRM",
            "Host open-house campaigns with email invites",
        ],
    },
    "beauty salon": {
        "keywords": ["beauty", "salon", "spa", "cosmetics", "makeup", "hair", "nails", "skincare"],
        "channels": ["Instagram", "TikTok", "Google Business Profile", "Facebook", "Booking Platform"],
        "ad_platforms": ["Instagram Ads", "Meta Ads", "Google Ads (Local)"],
        "content_types": ["Before/after transformations", "Tutorials", "Product showcases", "Client testimonials", "Seasonal looks"],
        "influencers": ["Beauty influencers", "Makeup artists", "Local micro creators"],
        "kpis": ["Appointment bookings", "New client acquisition", "Repeat visits", "Instagram reach", "Reviews"],
        "positioning": "Position the salon around signature looks, expert stylists and a premium pampering experience.",
        "social_platforms": ["Instagram", "TikTok", "Facebook"],
        "seo_terms": ["salon near me", "hair salon {city}", "best makeup artist {city}", "nail salon {city}"],
        "email_angles": ["Seasonal offers", "New services", "Loyalty program", "Before/after showcases", "Re-booking reminders"],
        "tactics": [
            "Post daily before/after transformations and tutorials",
            "Run Instagram Ads targeting nearby audiences",
            "Partner with beauty influencers for content",
            "Optimize Google Business Profile and collect reviews",
            "Launch a booking-driven offer campaign",
        ],
    },
    "hospital": {
        "keywords": ["hospital", "clinic", "medical", "healthcare", "doctor", "dental", "diagnostics", "care"],
        "channels": ["Google Ads (Local)", "Google Business Profile", "Facebook", "Local SEO", "Patient Referrals"],
        "ad_platforms": ["Google Search Ads", "Meta Ads", "YouTube Ads"],
        "content_types": ["Doctor explainers", "Patient testimonials", "Health education", "Facility tours", "FAQs"],
        "influencers": ["Medical professionals", "Health educators", "Local wellness creators"],
        "kpis": ["Appointments booked", "Patient inquiries", "New patient acquisition", "Online reviews", "Response time"],
        "positioning": "Position the clinic/hospital around trusted expertise, caring staff and clear patient outcomes.",
        "social_platforms": ["Facebook", "Instagram", "YouTube"],
        "seo_terms": ["{specialty} doctor {city}", "hospital near me", "best clinic {city}", "{service} in {city}"],
        "email_angles": ["Health checkup reminders", "Seasonal health tips", "New services", "Patient education", "Follow-up care"],
        "tactics": [
            "Run Google Ads on high-intent specialty and 'near me' searches",
            "Optimize Google Business Profile with services and photos",
            "Publish doctor-led explainer content for trust",
            "Collect and showcase patient reviews",
            "Build a referral and follow-up workflow",
        ],
    },
    "clinic": {
        "keywords": ["clinic", "hospital", "medical", "healthcare", "doctor", "dental", "diagnostics"],
        "channels": ["Google Ads (Local)", "Google Business Profile", "Facebook", "Local SEO", "Patient Referrals"],
        "ad_platforms": ["Google Search Ads", "Meta Ads", "YouTube Ads"],
        "content_types": ["Doctor explainers", "Patient testimonials", "Health education", "Facility tours", "FAQs"],
        "influencers": ["Medical professionals", "Health educators", "Local wellness creators"],
        "kpis": ["Appointments booked", "Patient inquiries", "New patient acquisition", "Online reviews", "Response time"],
        "positioning": "Position the clinic around trusted expertise, caring staff and clear patient outcomes.",
        "social_platforms": ["Facebook", "Instagram", "YouTube"],
        "seo_terms": ["{specialty} doctor {city}", "clinic near me", "best clinic {city}", "{service} in {city}"],
        "email_angles": ["Health checkup reminders", "Seasonal health tips", "New services", "Patient education", "Follow-up care"],
        "tactics": [
            "Run Google Ads on high-intent specialty and 'near me' searches",
            "Optimize Google Business Profile with services and photos",
            "Publish doctor-led explainer content for trust",
            "Collect and showcase patient reviews",
            "Build a referral and follow-up workflow",
        ],
    },
    "healthcare": {
        "keywords": ["healthcare", "hospital", "clinic", "medical", "doctor", "wellness"],
        "channels": ["Google Ads (Local)", "Google Business Profile", "Facebook", "Local SEO", "Patient Referrals"],
        "ad_platforms": ["Google Search Ads", "Meta Ads", "YouTube Ads"],
        "content_types": ["Doctor explainers", "Patient testimonials", "Health education", "Facility tours", "FAQs"],
        "influencers": ["Medical professionals", "Health educators", "Local wellness creators"],
        "kpis": ["Appointments booked", "Patient inquiries", "New patient acquisition", "Online reviews", "Response time"],
        "positioning": "Position the practice around trusted expertise, caring staff and clear patient outcomes.",
        "social_platforms": ["Facebook", "Instagram", "YouTube"],
        "seo_terms": ["{specialty} doctor {city}", "healthcare near me", "best clinic {city}", "{service} in {city}"],
        "email_angles": ["Health checkup reminders", "Seasonal health tips", "New services", "Patient education", "Follow-up care"],
        "tactics": [
            "Run Google Ads on high-intent specialty and 'near me' searches",
            "Optimize Google Business Profile with services and photos",
            "Publish doctor-led explainer content for trust",
            "Collect and showcase patient reviews",
            "Build a referral and follow-up workflow",
        ],
    },
    "academy": {
        "keywords": ["academy", "school", "education", "training", "tutoring", "courses", "learning", "institute"],
        "channels": ["Facebook", "Instagram", "Google Ads", "YouTube", "WhatsApp Enrollment"],
        "ad_platforms": ["Meta Ads", "Google Search Ads", "YouTube Ads"],
        "content_types": ["Student success stories", "Class previews", "Teacher spotlights", "Course explainers", "Testimonials"],
        "influencers": ["Education creators", "Alumni advocates", "Parent community voices"],
        "kpis": ["Enrollment", "Lead inquiries", "Course completion", "Student satisfaction", "Referrals"],
        "positioning": "Position the academy around outcomes, teaching quality and clear career/learning paths.",
        "social_platforms": ["Facebook", "Instagram", "YouTube", "LinkedIn"],
        "seo_terms": ["best {subject} academy {city}", "{course} classes {city}", "online {subject} course", "{certification} training"],
        "email_angles": ["Open enrollment", "Early-bird discounts", "Student spotlights", "Webinar invites", "Alumni outcomes"],
        "tactics": [
            "Run Meta Ads with course and outcome-focused creative",
            "Use Google Search Ads on course-intent keywords",
            "Publish student success stories and class previews",
            "Enable WhatsApp enrollment for quick follow-up",
            "Launch open-enrollment campaigns with early-bird offers",
        ],
    },
    "education": {
        "keywords": ["education", "academy", "school", "training", "tutoring", "courses", "institute"],
        "channels": ["Facebook", "Instagram", "Google Ads", "YouTube", "WhatsApp Enrollment"],
        "ad_platforms": ["Meta Ads", "Google Search Ads", "YouTube Ads"],
        "content_types": ["Student success stories", "Class previews", "Teacher spotlights", "Course explainers", "Testimonials"],
        "influencers": ["Education creators", "Alumni advocates", "Parent community voices"],
        "kpis": ["Enrollment", "Lead inquiries", "Course completion", "Student satisfaction", "Referrals"],
        "positioning": "Position the institution around outcomes, teaching quality and clear learning paths.",
        "social_platforms": ["Facebook", "Instagram", "YouTube", "LinkedIn"],
        "seo_terms": ["best {subject} academy {city}", "{course} classes {city}", "online {subject} course", "{certification} training"],
        "email_angles": ["Open enrollment", "Early-bird discounts", "Student spotlights", "Webinar invites", "Alumni outcomes"],
        "tactics": [
            "Run Meta Ads with course and outcome-focused creative",
            "Use Google Search Ads on course-intent keywords",
            "Publish student success stories and class previews",
            "Enable WhatsApp enrollment for quick follow-up",
            "Launch open-enrollment campaigns with early-bird offers",
        ],
    },
    "travel agency": {
        "keywords": ["travel", "tourism", "agency", "tours", "vacation", "holiday", "trip", "destination"],
        "channels": ["Instagram", "Facebook", "Google Ads", "YouTube", "Email Campaigns"],
        "ad_platforms": ["Meta Ads", "Google Search Ads", "YouTube Ads", "Instagram Ads"],
        "content_types": ["Destination reels", "Travel guides", "Customer trip stories", "Seasonal packages", "Virtual tours"],
        "influencers": ["Travel influencers", "Destination creators", "Lifestyle bloggers"],
        "kpis": ["Package inquiries", "Bookings", "Lead quality", "Repeat customers", "Newsletter signups"],
        "positioning": "Position the agency around curated experiences, seamless planning and unforgettable trips.",
        "social_platforms": ["Instagram", "YouTube", "Facebook", "TikTok"],
        "seo_terms": ["{destination} packages", "travel agency {city}", "cheap flights {city}", "best tours {destination}"],
        "email_angles": ["Seasonal packages", "Flash sales", "Destination guides", "Customer stories", "Early-bird deals"],
        "tactics": [
            "Produce destination reels and travel guides",
            "Run Meta and Instagram Ads on seasonal packages",
            "Use Google Search Ads on destination-intent keywords",
            "Build an email list with destination guides",
            "Partner with travel influencers for reach",
        ],
    },
    "furniture store": {
        "keywords": ["furniture", "store", "home", "interior", "sofa", "bedroom", "decor"],
        "channels": ["Instagram", "Facebook", "Google Ads", "Pinterest", "Google Business Profile"],
        "ad_platforms": ["Meta Ads", "Google Search Ads", "Instagram Ads", "Pinterest Ads"],
        "content_types": ["Room makeovers", "Product showcases", "Style guides", "Customer homes", "Before/after"],
        "influencers": ["Interior design creators", "Home decor influencers", "Local stylists"],
        "kpis": ["Store visits", "Online orders", "Lead inquiries", "Catalogue views", "Repeat purchases"],
        "positioning": "Position the store around style, quality materials and making every home beautiful.",
        "social_platforms": ["Instagram", "Pinterest", "Facebook", "TikTok"],
        "seo_terms": ["furniture store {city}", "sofa set {city}", "bedroom furniture online", "modern furniture {city}"],
        "email_angles": ["Seasonal sales", "New arrivals", "Room inspiration", "Financing options", "Delivery promos"],
        "tactics": [
            "Showcase room makeovers and style guides",
            "Run Meta and Pinterest Ads with strong visuals",
            "Use Google Search Ads on high-intent furniture keywords",
            "Optimize Google Business Profile for local visits",
            "Partner with interior design creators",
        ],
    },
    "e-commerce": {
        "keywords": ["ecommerce", "e-commerce", "online store", "shop", "retail", "dropshipping", "marketplace"],
        "channels": ["Meta Ads", "Google Shopping", "Instagram", "Email Automation", "TikTok", "Marketplace"],
        "ad_platforms": ["Meta Ads", "Google Shopping", "TikTok Ads", "Instagram Ads"],
        "content_types": ["Product videos", "Unboxings", "User-generated content", "Offer posts", "Style/use guides"],
        "influencers": ["Niche product influencers", "Unboxing creators", "Micro creators"],
        "kpis": ["Conversion rate", "Average order value", "Cart abandonment", "Repeat purchase rate", "Ad ROAS"],
        "positioning": "Position the store around product quality, fast delivery and a frictionless buying experience.",
        "social_platforms": ["Instagram", "TikTok", "Facebook", "Pinterest"],
        "seo_terms": ["buy {product}", "{product} online", "best {product} {country}", "{product} price"],
        "email_angles": ["Cart recovery", "Product launches", "Flash sales", "Loyalty rewards", "Abandoned browse"],
        "tactics": [
            "Run Meta and Google Shopping campaigns on top sellers",
            "Build cart-abandonment email automation",
            "Use TikTok and Instagram for product discovery",
            "Collect and feature user-generated content",
            "Optimize product pages for conversion and SEO",
        ],
    },
    "ecommerce": {
        "keywords": ["ecommerce", "e-commerce", "online store", "shop", "retail", "dropshipping"],
        "channels": ["Meta Ads", "Google Shopping", "Instagram", "Email Automation", "TikTok", "Marketplace"],
        "ad_platforms": ["Meta Ads", "Google Shopping", "TikTok Ads", "Instagram Ads"],
        "content_types": ["Product videos", "Unboxings", "User-generated content", "Offer posts", "Style/use guides"],
        "influencers": ["Niche product influencers", "Unboxing creators", "Micro creators"],
        "kpis": ["Conversion rate", "Average order value", "Cart abandonment", "Repeat purchase rate", "Ad ROAS"],
        "positioning": "Position the store around product quality, fast delivery and a frictionless buying experience.",
        "social_platforms": ["Instagram", "TikTok", "Facebook", "Pinterest"],
        "seo_terms": ["buy {product}", "{product} online", "best {product} {country}", "{product} price"],
        "email_angles": ["Cart recovery", "Product launches", "Flash sales", "Loyalty rewards", "Abandoned browse"],
        "tactics": [
            "Run Meta and Google Shopping campaigns on top sellers",
            "Build cart-abandonment email automation",
            "Use TikTok and Instagram for product discovery",
            "Collect and feature user-generated content",
            "Optimize product pages for conversion and SEO",
        ],
    },
    "agency": {
        "keywords": ["agency", "marketing agency", "digital agency", "creative agency", "consulting"],
        "channels": ["LinkedIn", "Google Ads", "Referrals", "Content Marketing", "Email Outreach"],
        "ad_platforms": ["Google Search Ads", "LinkedIn Ads", "YouTube Ads"],
        "content_types": ["Case studies", "Industry insights", "Frameworks", "Webinars", "Client results"],
        "influencers": ["Industry thought leaders", "Founder voices", "Podcast guests"],
        "kpis": ["Qualified leads", "Proposals sent", "Win rate", "Retainer clients", "Referral rate"],
        "positioning": "Position the agency around proven results, senior expertise and a clear specialty.",
        "social_platforms": ["LinkedIn", "YouTube", "X"],
        "seo_terms": ["{niche} marketing agency", "best {service} agency", "{city} marketing agency", "{service} agency"],
        "email_angles": ["Case study drops", "New capability", "Webinar invites", "Thought leadership", "QBR insights"],
        "tactics": [
            "Run LinkedIn Ads targeting the ideal client profile",
            "Publish case studies and frameworks for authority",
            "Use Google Search Ads on service-intent keywords",
            "Build an outbound + referral engine",
            "Host webinars and thought-leadership content",
        ],
    },
    "hospitality": {
        "keywords": ["hotel", "hospitality", "resort", "airbnb", "hostel", "stay", "lodging"],
        "channels": ["Booking Platforms", "Google Ads", "Instagram", "TripAdvisor/Reviews", "Email"],
        "ad_platforms": ["Google Ads (Local)", "Meta Ads", "Instagram Ads"],
        "content_types": ["Room tours", "Guest experiences", "Local guides", "Seasonal offers", "Review highlights"],
        "influencers": ["Travel influencers", "Local experience creators", "Food/travel bloggers"],
        "kpis": ["Direct bookings", "Occupancy rate", "Review score", "Repeat guests", "Website conversion"],
        "positioning": "Position the property around memorable stays, local charm and outstanding hospitality.",
        "social_platforms": ["Instagram", "Facebook", "TikTok", "YouTube"],
        "seo_terms": ["hotel in {city}", "best stay {city}", "{city} accommodation", "{city} boutique hotel"],
        "email_angles": ["Direct booking offers", "Seasonal packages", "Guest follow-ups", "Local experiences", "Loyalty perks"],
        "tactics": [
            "Drive direct bookings with Google Ads and offers",
            "Produce room tours and guest experience content",
            "Manage reviews actively on booking platforms",
            "Partner with travel influencers for reach",
            "Build a direct-booking email list",
        ],
    },
    "automotive": {
        "keywords": ["car", "automotive", "dealership", "auto", "vehicles", "garage", "workshop"],
        "channels": ["Google Ads", "Facebook", "YouTube", "Local SEO", "Showroom Events"],
        "ad_platforms": ["Google Search Ads", "Meta Ads", "YouTube Ads"],
        "content_types": ["Vehicle walkarounds", "Test drive stories", "Service tips", "Customer reviews", "Comparisons"],
        "influencers": ["Auto reviewers", "Local car creators", "Motorsport voices"],
        "kpis": ["Test drive bookings", "Leads", "Sales", "Service bookings", "Showroom visits"],
        "positioning": "Position the dealership/garage around honest service, quality vehicles and trust.",
        "social_platforms": ["YouTube", "Instagram", "Facebook", "TikTok"],
        "seo_terms": ["{brand} dealer {city}", "car service {city}", "buy {vehicle} {city}", "used cars {city}"],
        "email_angles": ["Service reminders", "New arrivals", "Test drive invites", "Seasonal checks", "Financing offers"],
        "tactics": [
            "Run Google Search Ads on model and service keywords",
            "Produce vehicle walkarounds for YouTube",
            "Host showroom and test-drive events",
            "Build service-reminder email automation",
            "Optimize local SEO and Google Business Profile",
        ],
    },
    "fintech": {
        "keywords": ["fintech", "finance", "banking", "payments", "lending", "insurance", "investing", "money"],
        "channels": ["Google Ads", "LinkedIn", "Content Marketing", "App Store Optimization", "Email"],
        "ad_platforms": ["Google Search Ads", "LinkedIn Ads", "YouTube Ads"],
        "content_types": ["Explainers", "Trust/security content", "Calculator tools", "Comparison guides", "Customer stories"],
        "influencers": ["Finance educators", "Personal finance creators", "Industry analysts"],
        "kpis": ["Signups", "Activation", "Transaction volume", "Retention", "Cost per acquisition"],
        "positioning": "Position the fintech around security, simplicity and real financial outcomes.",
        "social_platforms": ["LinkedIn", "YouTube", "X", "Instagram"],
        "seo_terms": ["best {category} app", "{product} review", "how to {outcome}", "{service} comparison"],
        "email_angles": ["Activation nudges", "Product updates", "Financial tips", "Security notices", "Retention offers"],
        "tactics": [
            "Run Google Search Ads on high-intent financial keywords",
            "Publish trust and education content",
            "Build activation email flows",
            "Optimize app store listing for organic growth",
            "Use LinkedIn Ads for B2B segments",
        ],
    },
    "jewelry": {
        "keywords": ["jewelry", "jewellery", "gold", "diamond", "watch", "accessories"],
        "channels": ["Instagram", "Facebook", "Google Ads", "Google Business Profile", "Email"],
        "ad_platforms": ["Meta Ads", "Instagram Ads", "Google Search Ads"],
        "content_types": ["Product close-ups", "Craftsmanship stories", "Festive collections", "Style guides", "Customer moments"],
        "influencers": ["Fashion influencers", "Bridal creators", "Lifestyle bloggers"],
        "kpis": ["Store visits", "Online orders", "Catalogue views", "Festive campaign sales", "Repeat buyers"],
        "positioning": "Position the jeweler around craftsmanship, trust and timeless design.",
        "social_platforms": ["Instagram", "Facebook", "Pinterest", "TikTok"],
        "seo_terms": ["gold jewelry {city}", "bridal jewelry {city}", "buy {item} online", "jewelry store {city}"],
        "email_angles": ["Festive collections", "New arrivals", "Bridal appointments", "Loyalty program", "Craft stories"],
        "tactics": [
            "Showcase craftsmanship and festive collections",
            "Run Meta and Instagram Ads on high-value visuals",
            "Use Google Search Ads on product keywords",
            "Optimize Google Business Profile for local visits",
            "Partner with bridal and fashion influencers",
        ],
    },
    "bakery": {
        "keywords": ["bakery", "baker", "cake", "pastry", "dessert", "confectionery"],
        "channels": ["Instagram", "Google Business Profile", "Food Delivery Apps", "Facebook", "Local SEO"],
        "ad_platforms": ["Meta Ads", "Instagram Ads", "Google Ads (Local)"],
        "content_types": ["Fresh-baked reels", "Cake showcase", "Behind-the-scenes", "Customer orders", "Seasonal treats"],
        "influencers": ["Local food influencers", "Dessert bloggers", "Instagram foodies"],
        "kpis": ["Online orders", "Custom cake bookings", "Delivery app ranking", "Google reviews", "Repeat orders"],
        "positioning": "Position the bakery around freshness, craft and irresistible treats.",
        "social_platforms": ["Instagram", "TikTok", "Facebook"],
        "seo_terms": ["bakery near me", "custom cakes {city}", "best bakery {city}", "cake delivery {city}"],
        "email_angles": ["Seasonal treats", "Custom cake promos", "Loyalty rewards", "New menu items", "Pre-order offers"],
        "tactics": [
            "Post fresh-baked content daily",
            "Optimize Google Business Profile with photos and reviews",
            "Partner with local food influencers",
            "Run delivery-app promotions to boost ranking",
            "Launch seasonal and custom-order campaigns",
        ],
    },
    "apparel": {
        "keywords": ["apparel", "clothing", "fashion", "brand", "wear", "streetwear"],
        "channels": ["Instagram", "TikTok", "Meta Ads", "Google Shopping", "Email"],
        "ad_platforms": ["Meta Ads", "TikTok Ads", "Google Shopping", "Instagram Ads"],
        "content_types": ["Lookbooks", "OOTD reels", "Styling tips", "User-generated content", "Drops"],
        "influencers": ["Fashion influencers", "Streetwear creators", "Micro style voices"],
        "kpis": ["Online sales", "Conversion rate", "Average order value", "Repeat purchase", "Ad ROAS"],
        "positioning": "Position the brand around a distinct aesthetic, quality fabrics and a community.",
        "social_platforms": ["Instagram", "TikTok", "Pinterest", "YouTube"],
        "seo_terms": ["buy {product}", "{style} clothing", "{product} online", "best {category} brand"],
        "email_angles": ["New drops", "Restocks", "Cart recovery", "Styling guides", "Loyalty rewards"],
        "tactics": [
            "Run Meta and TikTok Ads on lookbook creative",
            "Use Google Shopping for product discovery",
            "Build drops and restock email alerts",
            "Feature user-generated content heavily",
            "Partner with fashion influencers",
        ],
    },
}

DEFAULT_PLAYBOOK = {
    "channels": ["Google Ads", "Meta Ads", "Email Marketing", "Instagram", "LinkedIn"],
    "ad_platforms": ["Google Search Ads", "Meta Ads", "Instagram Ads"],
    "content_types": ["Educational posts", "Customer stories", "Product showcases", "Behind-the-scenes", "FAQs"],
    "influencers": ["Industry-relevant micro influencers", "Local creators", "Community voices"],
    "kpis": ["Qualified leads", "Conversions", "Engagement", "Customer acquisition cost", "Retention"],
    "positioning": "Position the business around a clear, differentiated value proposition and measurable results.",
    "social_platforms": ["Instagram", "Facebook", "LinkedIn"],
    "seo_terms": ["{product} {city}", "best {industry} {city}", "{service} near me", "{product} online"],
    "email_angles": ["Welcome series", "Promotions", "Product launches", "Customer stories", "Re-engagement"],
    "tactics": [
        "Run search and social campaigns on the highest-intent keywords",
        "Build an email automation flow for nurture and retention",
        "Publish a steady stream of educational and social proof content",
        "Partner with relevant micro influencers",
        "Retarget engaged audiences to lift conversion",
    ],
}


def match_playbook(industry: str | None) -> dict:
    """Return the best-matching industry playbook for an industry string."""
    if not industry:
        return DEFAULT_PLAYBOOK
    text = industry.strip().lower()
    for key, playbook in INDUSTRY_PLAYBOOKS.items():
        if any(kw in text for kw in playbook["keywords"]):
            return playbook
    return DEFAULT_PLAYBOOK


def format_playbook(playbook: dict) -> str:
    """Render a playbook as readable prompt lines."""
    lines = [
        "Preferred channels: " + ", ".join(playbook["channels"]),
        "Ad platforms: " + ", ".join(playbook["ad_platforms"]),
        "Content types: " + ", ".join(playbook["content_types"]),
        "Influencer strategy: " + ", ".join(playbook["influencers"]),
        "Social platforms: " + ", ".join(playbook["social_platforms"]),
        "Typical KPIs: " + ", ".join(playbook["kpis"]),
        "Positioning angle: " + playbook["positioning"],
    ]
    return "\n".join(lines)
